### ISSUE TITLE
Configurable Minicio Ore

### ISSUE THREAD

**Issue by MasterEnderman** [KillBait/PrimordialCrops#4]
The title says it all.
Would be great if you could configure the generation of the Minicio Ore.
In my opinion it spawns way to common.

Keep up the good work!

**Comment by KillBait** [comment]
that is actually something i never considered adding to the config, will look into it for sure, thanks for the suggestion :)

**Comment by KillBait** [comment]
Just released new version with the worldgen config options.

Enable/Disable Minicio ore generation completely
Chance to spawn per chunk (5 min, 40 max) ( default 20)
Min Z to spawn ore from (0 min, 64 max) ( default 5)
Max Z to spawn ore to (0 min, 64 max) ( default 64)

Hope this is what you requested, let me know if i missed anything
