### ISSUE TITLE
Crafting Bug

### ISSUE THREAD

**Issue by abused** [KillBait/PrimordialCrops#5]
Hey! Im using Prim in a modpack currently and there is a recipe bug with fire essence, 8 in a chest pattern makes minicio essence.

**Comment by KillBait** [comment]
hi, i'll look into it sometime tomorrow, thanks for letting me know

**Comment by KillBait** [comment]
my bad, added that recipe when was testing worldgen, forgot to take it out, will be removed for next version

**Comment by KillBait** [comment]
Just released new version with the recipe removed.
